[package]
name = "searcher"
version = "0.1.0"
authors = ["Ramen Deer <ramendeer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simd-json = "0.2.5"
serde_json = "1.0.48"
